# Generated by Django 3.1.7 on 2021-03-26 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='link',
            new_name='title',
        ),
    ]
