# Generated by Django 3.1.7 on 2021-03-29 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210326_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
