# Generated by Django 3.1.7 on 2021-03-29 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210329_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='total',
        ),
        migrations.AlterField(
            model_name='result',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
